/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Phani_Kadali' at '6/21/16 1:36 AM' with Gradle 2.14
 *
 * @author Phani_Kadali, @date 6/21/16 1:36 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
